### PR TITLE
[PT-3602] Print a warning when enhanced metrics are disabled in the target

### PR DESCRIPTION
**Pull request by spetrashov**
Currently, the exporter crashes when one of the targets has enhanced metrics disabled. 
It gonna keep checking the RDS and print warnings in the log, would be cool to remove the instance from the loop. But if we are going to run it with `--log.level="error"`, it shouldn't cause us troubles.

### CODE REVIEW

**Comment by rafaeljesus** [comment]
should we contribute to the main repo?

**Comment by CVirus** [comment]
> should we contribute to the main repo?

I'm not sure to be honest.
They already have an open ticket for it that wasn't touch for over a month now https://jira.percona.com/browse/PMM-3588

**Comment by CVirus** [comment]
:+1:

**Comment by rafaeljesus** [comment]
gotcha! let's test this out and contribute back, so whenever they have the chance to merge it and shift back to their fork

**Comment by rafaeljesus** [comment]
:shipit:

**Pull request merged**
